---
- name: "Uninstall Helm on Bastion hosts"
  hosts: "bastion,k8s_bastion,ocp_bastion"
  gather_facts: "true"

  tasks:
    - name: "Uninstall Helm"
      ansible.builtin.package:
        name: helm
        state: absent
      become: true
      register: helm_install_res

    - name: "Uninstall Helm result"
      ansible.builtin.debug:
        var: helm_install_res
        verbosity: 2
...
